# Bridge for simulation time (Gazebo -> ROS2)
- ros_topic_name: "clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS

# Bridge for joint states (Gazebo -> ROS2) for RViz visualization
- ros_topic_name: "/joint_states"
  gz_topic_name: "/world/default/model/spider/joint_state"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: GZ_TO_ROS

# --------------------------------------------------------------------
# Bridges for Joint Commands (ROS2 -> Gazebo) - THIS IS THE CONTROL PART
# --------------------------------------------------------------------

# --- Front Left Leg (f1) ---
- ros_topic_name: "/f1_joint/cmd_pos"
  gz_topic_name: "/model/spider/joint/f1_joint/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/f11_joint/cmd_pos"
  gz_topic_name: "/model/spider/joint/f11_joint/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/f111_joint/cmd_pos"
  gz_topic_name: "/model/spider/joint/f111_joint/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

# --- Front Right Leg (f2) ---
- ros_topic_name: "/f2_joint/cmd_pos"
  gz_topic_name: "/model/spider/joint/f2_joint/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/f22_joint/cmd_pos"
  gz_topic_name: "/model/spider/joint/f22_joint/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/f222_joint/cmd_pos"
  gz_topic_name: "/model/spider/joint/f222_joint/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

# --- Back Left Leg (b1) ---
- ros_topic_name: "/b1_joint/cmd_pos"
  gz_topic_name: "/model/spider/joint/b1_joint/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/b11_joint/cmd_pos"
  gz_topic_name: "/model/spider/joint/b11_joint/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/b111_joint/cmd_pos"
  gz_topic_name: "/model/spider/joint/b111_joint/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

# --- Back Right Leg (b2) ---
- ros_topic_name: "/b2_joint/cmd_pos"
  gz_topic_name: "/model/spider/joint/b2_joint/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/b22_joint/cmd_pos"
  gz_topic_name: "/model/spider/joint/b22_joint/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/b222_joint/cmd_pos"
  gz_topic_name: "/model/spider/joint/b222_joint/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
